---
 - hosts: all
   become: true
   tasks: 
        - name: "Add a line to a file if it does not exists. Without passing regexp"
          lineinfile:
                  path: /tmp/testfile
                  line: '192.168.1.99   foo.lab.net     foo'
        
        - name: "Fully quoted because of the : on the line. See the Gotchas in the YAML docs"
          lineinfile:
                  path: /etc/sudoers
                  state: present
                  regex: '^%wheel\s'
                  line: '%wheel ALL=(ALL) NOPASSWD: ALL' 
